#DEBUG VARIABLES - Use if you are experiencing any errors
enableIgnoreUnbreakingChecks: false
enableIgnoreSkipForBasegameItems: false
ENABLE-DEBUG: false
language: en
FriendlyFireEnabled: false
showPossibleCrashHelpMessage: true
Enable_Creation_Of_Default_Files: true
unknownTranslationKeyFixer: false
enable_permssionsToShoot: false


#Resourcepack settings.

useDefaultResourcepack: true
DefaultResourcepackOverride: false
DefaultResourcepack: https://www.dropbox.com/s/g5rkfdcmlax9w6a/QualityArmoryV2.0.2.zip?dl=1
KickPlayerIfDeniedResourcepack: false
sendOnJoin: true
sendTitleOnJoin: false
SecondsTillRPIsSent: 0.0
Auto-Detect-Resourcepack: true
ManuallyOverrideTo_1_8_systems: false
ManuallyOverrideTo_1_13_systems: false

# How much should QA check for block corners?
BulletDetection:
  step: 0.1

#Which blocks should stop bullets?
BlockBullets:
  door: false
  halfslabs: false
  leaves: false
  water: false
  glass: false
#Can players click on chests with guns?
enableInteract:
  Chests: false

#Bullet Trails
enableBulletTrails: true
BulletTrailsSpacing: 0.5

Items:
  enable_Unbreaking: true
experimental:
  BulletWounds:
    InitialBloodLevel: 1500.0
    BloodIncreasePerSecond: 0.01
    Medkit_Heal_Bloodloss_Rate: 0.05
    enableBleeding: false

#Enable if you have problems with the hotbar messages.
disableHotbarMessages:
  OutOfAmmo: false
  Shoot: false
  Reload: false

#Some default values determineing gun accuracy when shooting
generalModifiers:
  sway:
    Run: 2.0
    Walk: 1.5
    Ironsights: 0.8
    Sneak: 0.7

EnableWeaponDurability: false
overrideAnvil: false
verboseItemLogging: false
enableIgnoreArmorProtection: false
enableReloadingWhenSwapToOffhand: true
enableReloadOnlyWhenSwapToOffhand: false
allowGunHitEntities: false
showOutOfAmmoOnTitle: false
showReloadingTitle: false
enableExplosionDamage: false
enableExplosionDamageDrop: false
enablePrimaryWeaponLimiter: false
weaponlimiter_primaries: 2
weaponlimiter_secondaries: 2
enableCrafting: true
enableShop: true
AUTO-UPDATE: true
Swap-Reload-and-Shooting-Controls: false
Order-Shop-By-Price: false
enable_lore_gun-info_messages: true
enable_lore_control-help_messages: true
Enable_Headshot_Instantkill: false
Enable_Headshot_Notification_Sound: false
Headshot_Notification_Sound: entity.experience_orb.pickup
Enable_Headshot_Sounds: true
gravityConstantForDropoffCalculations: 0.05
allowGunReload: true
EnableGlowEffects: false
Break-Block-Texture-If-Shot: true
enableRecoil: true
automaticallyReloadGunWhenOutOfAmmo: false
impenetrableEntityTypes:
  - ARROW
IronSightsOnRightClick: false
SwapSneakToSingleFile: false
DestructableMaterials:
  - MATERIAL_NAME_HERE